/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {    colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        customPurple: "#1D052C",
        customLightPurple: "#AF5AD0",
        lightPink: "#F6F0E5",
        skyBlue: "#1DC5C4",
        lightGray: "#F6F6F6",
        darkBlue: "#103883",
        lightBlue: "#E5F0F6",
        paleAqua: "#E6F1F0",
        pink: "#F7EDEC",
        lightPurple: "#EAE5F1",
        cream: "#F3EBE4",
        darkGray: "#E6E6E6",
        textGray:"#999999",
        customButton :'#333333',
        priceColor: "#6C7275",
        textgraycolor:"#666666",
        deepTeal:"#0D3F3F",
        mediumGray: "#F9F9F9",
        lightMistGray:"#F3F5F7",
        paleBlue:"#C3D4F3",
        darkPurple:"#1D052C",
        signupbg:"#1D052C",
        cardGreen:"#5EBD68",
        cardGray:"#F6F6F6",
        cardViolet:"#774889",
        lightRed:"#FF7D7D",
        limeGreen:"#0BB42A",
        iconGray:"#C2C6CE",
        lightOrange:"#FFA600",
        bgFooter:'#003434',
        signuptext:'#034A9F'
      },},
  },
    safelist: [
    "bg-lightPink",
    "bg-lightBlue",
    "bg-paleAqua",
    "bg-pink",
    "bg-lightPurple",
    "bg-cream",
    "bg-cardGreen",
    "bg-cardViolet",
    "bg-cardGray",
  ],
  plugins: [],
}